---
title: "DSO545_Final_Project"
author: "Yu Dong"
date: "11/17/2016"
output: html_document
---

Load dataset and packages

```{r load}
setwd("~/Desktop/DSO545/Final project")
# load("processed1.RData")
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
tracking_data = read.csv("raw data/311_Call_Center_Tracking_Data.csv")
request_data = read.csv("raw data/MyLA311_Service_Request_Data_2016.csv")
```

Preprocess the data

```{r preprocess}
tracking_data$Date = mdy(tracking_data$Date)
tracking_data$Time = hms(tracking_data$Time)
request_data$CreatedDate = mdy_hms(request_data$CreatedDate)
request_data$UpdatedDate = mdy_hms(request_data$UpdatedDate)
# since there are lots of observations like xx/xx/xxxx 12:00:00AM which leads to unaccurate time records, remove the hour-minute_seconds part
request_data$ServiceDate = str_replace_all(request_data$ServiceDate, " [0-9]{2}:[0-9]{2}:[0-9]{2} [AP]M", "")
request_data$ServiceDate = mdy(request_data$ServiceDate)
# attention: there are many obviously unreasonable records: many records with service date of 1900/01/01, and some other service dates in 2017 or later
request_data$ClosedDate = mdy_hms(request_data$ClosedDate)
```

backup the data

```{r backup}
tracking_backup = tracking_data
request_backup = request_data
```

calculate new varibales

1. tracking data  
```{r new vars1}
# pay attention to this month variables, since the data varies from 2011/01 to 2016/05, so Jan-May will have relatively more records.
tracking_data$month = month(tracking_data$Date)
tracking_data$weekday = wday(tracking_data$Date, label = TRUE)
tracking_data$hour = hour(tracking_data$Time)
```

2. request data  
```{r new vars2}
# extract the month, weekday and hour the request created, not updated
request_data$month_created = month(request_data$CreatedDate)
request_data$weekday_created = wday(request_data$CreatedDate, label = TRUE)
request_data$hour_created = hour(request_data$CreatedDate)
request_data$response_period = round(
    (request_data$ClosedDate - request_data$CreatedDate) / (60 * 60),
    2)

# the percentage of unclosed requests: 0.546
nrow(filter(request_data, is.na(ClosedDate)))/ nrow(request_data)
```

